DROP TABLE IF EXISTS names;

CREATE TABLE IF NOT EXISTS names (
	name TEXT NOT NULL PRIMARY KEY,
	owner TEXT NOT NULL,
	texts TEXT,
	addresses TEXT,
	contenthash TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS job_posts;

CREATE TABLE IF NOT EXISTS job_posts (
    id SERIAL PRIMARY KEY,
    image_url TEXT,
    title TEXT NOT NULL,
    description TEXT,
    author TEXT NOT NULL,
    candidates TEXT[],
    expiry_date DATE,
    website_url TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
