name = "ens-gateway"
main = "src/index.ts"
compatibility_date = "2023-03-15"

[[d1_databases]]
binding = "DB"
database_name = "constellation"
database_id = "8312edce-ca9e-4a97-a9db-b081f665cb4e"

# The necessary secrets are:
# - PRIVATE_KEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
